services:
#  frontend:
#    image: node:24.14.0-alpine
#    container_name: frontend
#    working_dir: /app
#    volumes:
#      - ./front:/app
#    ports:
#      - "${FRONTEND_PORT:-80}:5173"
#    environment:
#      - VITE_STRAPI_URL=http://localhost:1337
#    command: >
#      sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
#    restart: unless-stopped
#    depends_on:
#      - strapi

  strapi:
    image: node:24.14.0-alpine
    container_name: strapi
    working_dir: /opt/app
    volumes:
      - ./back/strapi:/opt/app
      - ./shared:/opt/app/src/shared
      - ./back/strapi_data/.tmp:/opt/app/.tmp
      - ./back/strapi_data/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    env_file: .env
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: development
    command: >
      sh -c "npm install && npm run develop"
    restart: unless-stopped
