/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1a1a2b",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#333345",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-tertiary-fixed": "#261a00",
        "on-primary-container": "#00566a",
        "on-surface": "#e3e0f8",
        "primary-container": "#00d2ff",
        "surface-tint": "#47d6ff",
        "on-background": "#e3e0f8",
        "on-primary-fixed-variant": "#004e60",
        "primary-fixed-dim": "#47d6ff",
        "surface-dim": "#121222",
        "error": "#ffb4ab",
        "surface-container-lowest": "#0c0c1d",
        "secondary-container": "#6f00be",
        "on-surface-variant": "#bbc9cf",
        "on-secondary-container": "#d6a9ff",
        "outline": "#859399",
        "tertiary-fixed-dim": "#fbbc00",
        "inverse-surface": "#e3e0f8",
        "tertiary-fixed": "#ffdfa0",
        "on-primary": "#003543",
        "surface": "#121222",
        "surface-variant": "#333345",
        "tertiary": "#ffd889",
        "surface-container": "#1e1e2f",
        "surface-bright": "#38374a",
        "on-tertiary-container": "#664a00",
        "on-error": "#690005",
        "inverse-primary": "#00677f",
        "on-secondary-fixed": "#2c0051",
        "secondary-fixed-dim": "#ddb7ff",
        "outline-variant": "#3c494e",
        "secondary": "#ddb7ff",
        "background": "#121222",
        "secondary-fixed": "#f0dbff",
        "surface-container-high": "#29283a",
        "on-secondary-fixed-variant": "#6900b3",
        "on-secondary": "#490080",
        "on-primary-fixed": "#001f28",
        "on-tertiary": "#402d00",
        "error-container": "#93000a",
        "tertiary-container": "#f5b700",
        "primary-fixed": "#b6ebff",
        "primary": "#a5e7ff",
        "inverse-on-surface": "#2f2f40"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
